name: Dart CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
      
    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release
