name: Dart CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - name: Install dependencies
      run: pub get
    - name: Build flutter apk
      run: flutter build apk
